DELETE FROM payment_history;
DELETE FROM mcc;
DELETE FROM balance;
DELETE FROM merchant;
DELETE FROM account;
DELETE FROM category;

ALTER TABLE account ALTER COLUMN id RESTART WITH 1;
ALTER TABLE category ALTER COLUMN id RESTART WITH 1;
ALTER TABLE balance ALTER COLUMN id RESTART WITH 1;
ALTER TABLE mcc ALTER COLUMN id RESTART WITH 1;
ALTER TABLE payment_history ALTER COLUMN id RESTART WITH 1;
ALTER TABLE merchant ALTER COLUMN id RESTART WITH 1;